### ISSUE TITLE
Clearine does not work anymore with python 3.8

### ISSUE THREAD

**Issue by bthiebault** [okitavera/clearine#11]
Since I updated python to 3.8, clearine does not start.

I have the following error message:
```

Traceback (most recent call last):
  File "/usr/bin/clearine", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Clearine==0.6' distribution was not found and is required by the application
```

I'm using the clearine-git  0.7.r2.g35e1a78-1 version available on the AUR (I use Arch BTW)

**Comment by okitavera** [comment]
it probably due to outdated version number on [`setup.py`](https://github.com/okitavera/clearine/blob/master/setup.py)

**Comment by bthiebault** [comment]
What can I do to help debugging?

**Comment by lambdaclan** [comment]
Hello,

I am assuming you are running an Arch based distro?  After I did some quick digging, the issue seems to be with the update to Python 3.8 and has nothing to do with the tool itself. 

Look at this [reddit](https://www.reddit.com/r/archlinux/comments/9aejrq/updating_to_python_37_broke_a_heap_of_stuff_i/) thread for the same issue occurring with the Python 3.7 update.

This is because after the upgrade pip and Python package libraries are conflicted as to which one to use.

As per the thread:

>> You are responsible for rebuilding AUR packages when updates like this happen

In order to fix the issue you simply need to uninstall and clean install clearine one more time. Keep in mind this is necessary for all Python packages that have the same issue.

```
sudo pacman -Rns clearine-git
yay -S clearine-git
```
Make sure to clean install when prompted.

Hope this helps :+1:

**Comment by bthiebault** [comment]
Yes, I'm using Arch.
And yes, removing the package and rebuilding it fixed the problem.
Thank you for your help!
